
services:
  api:
    container_name: node-ex01
    image: node:20.18.0
    working_dir: /app/node-ex01
    volumes:
      - "./node-ex01:/app/node-ex01"
    ports:
      - "3000:3000"
    command: [ "npx", "nodemon", "--legacy-watch", "index.js" ]

  db:
    container_name: f8-node-db
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - '4000:5432'
    volumes:
      - './db:/var/lib/postgresql/data'
volumes:
  db:
    driver: local