// "use client";

// import { useRouter } from "next/navigation";

export const metadata = {
  title: "Quan ao tre em",
  description: "Generated by create next app",
};
export default function page(params) {
  console.log(params);

  //   const router = useRouter();
  const onAccessDetail = () => {
    router.push("products/1");
  };
  return (
    <>
      <h1>Hello this is product page</h1>
      {/* <button
        className="rounded bg-red-500"
        onClick={() => {
          onAccessDetail();
        }}
      >
        Chuyển trang
      </button> */}
    </>
  );
}
