
services:
  api:
    container_name: nestjs01
    image: node:20.18.0
    working_dir: /app/nestjs
    env_file:
      - nest/.env
    volumes:
      - "./nest:/app/nestjs"
    ports:
      - "3000:3000"
    command: [ "npm", "run", "start:dev", "index.js" ]

  db:
    container_name: f8-nestjs-db
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - '4000:5432'
    volumes:
      - './nest/db:/var/lib/postgresql/data'
volumes:
  db:
    driver: local