version: "3.8"

services:
  web:
    container_name: F8-react-docker
    image: custome-node:241009
    volumes:
      - ".:/app"
    ports:
      - "3000:5173"
    command: ["npm","run","dev"]
    # build:
    #   context: .
    #   dockerfile: Dockerfile
